name: Create Release

on:
  workflow_dispatch:
    inputs:
      package_tag:
        type: string
        required: true

jobs:
  create-packages:
      uses: ./.github/workflows/cmake-multi-platform-build-and-test.yml
      permissions:
        contents: write
      with:
        create_package: true
        package_tag: ${{ github.event.inputs.package_tag }}
